# Generated by Django 5.2.1 on 2025-05-22 16:45

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventchangelog',
            name='event_chang_event_i_570549_idx',
        ),
        migrations.AlterField(
            model_name='eventchangelog',
            name='change_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('permission_add', 'Permission Add'), ('permission_update', 'Permission Update'), ('permission_delete', 'Permission Delete'), ('field_update', 'Field Update')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventchangelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventchangelog',
            name='new_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='eventchangelog',
            name='new_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_version_changes', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventchangelog',
            name='old_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_version_changes', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventchangelog',
            name='previous_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterModelTable(
            name='eventchangelog',
            table=None,
        ),
    ]
